services:
  - type: web
    name: hairsalon
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    # Nếu bạn dùng startCommand thì phải đúng, nhưng Dockerfile đã có CMD rồi nên có thể bỏ dòng này
    # startCommand: apache2-foreground
    autoDeploy: true
